### ISSUE TITLE
fatal error: exitsyscall: syscall frame is no longer valid

### ISSUE THREAD

**Issue by errordeveloper** [mitchellh/go-mruby#49]
ref https://github.com/errordeveloper/kubeplay/issues/1

I've not yet been able to find what's the simplest way to reproduce this, but I am able to hit this with my project, which you can compile like this:
```
go get github.com/Masterminds/glide
go get -d github.com/errordeveloper/kubeplay
cd $GOPATH/src/github.com/errordeveloper/kubeplay
$GOPATH/bin/glide up
make -C vendor/github.com/mitchellh/go-mruby libmruby.a
go install ./rubykube
go build .
```

Create empty `kubeconfig`:
```YAML
kind: Config
apiVersion: v1
preferences: {}
clusters:
- cluster:
    server: https://localhost:8443
  name: test
contexts:
- context:
    cluster: test
    user: test
  name: test
current-context: test
users:
- name: test
  user: {}
```

Start `kubeplay` and call `pods []`:
```
> ./kubeplay -kubeconfig ./kubeconfig
kubeplay (namespace="*")> pods []
+++ Execute: pods 
args=[]
fatal error: exitsyscall: syscall frame is no longer valid
```
